name: NPM

on:
  push:
    branches:
      - main
    paths:
      - "contracts/**"
      - "migrations/scripts/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  npm-publish-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Bump up package version
        id: npm-version-bump
        uses: keep-network/npm-version-bump@v2
        with:
          environment: dev
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
