name: Test Solidity

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "11.x"
      - name: Authenticate GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_GITHUB_TOKEN }}" >> .npmrc
      - name: Install dependencies
        run: npm install
      - name: Run tests
        # Runs ganache in background
        run: |
          npm run ganache & 
          npm test
        env:
          CI: true
